     ---------------------------- Error(2018-11-29 09:52:26.6213) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : System.NullReferenceException
      
              Exception Message : Referencia a objeto no establecida como instancia de un objeto.
     
              Inner Exception  : System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Proveduria.Controllers.ItemController.<>c.<SearchItemsFiltro>b__5_6(<>f__AnonymousType7`2 <>h__TransparentIdentifier1) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\ItemController.cs:línea 115
   en System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   en System.Linq.Enumerable.<TakeIterator>d__24`1.MoveNext()
   en System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   en System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   en Proveduria.Controllers.ItemController.SearchItemsFiltro(String filtro, String pagina) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\ItemController.cs:línea 112 
 
              Stack Trace   :    en Proveduria.Controllers.ItemController.<>c.<SearchItemsFiltro>b__5_6(<>f__AnonymousType7`2 <>h__TransparentIdentifier1) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\ItemController.cs:línea 115
   en System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   en System.Linq.Enumerable.<TakeIterator>d__24`1.MoveNext()
   en System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   en System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   en Proveduria.Controllers.ItemController.SearchItemsFiltro(String filtro, String pagina) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\ItemController.cs:línea 112
        
              Additional Info  : Referencia a objeto no establecida como instancia de un objeto.  
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Error(2018-11-29 09:52:27.6672) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : System.NullReferenceException
      
              Exception Message : Referencia a objeto no establecida como instancia de un objeto.
     
              Inner Exception  : System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Proveduria.Controllers.ItemController.<>c.<SearchItemsFiltro>b__5_6(<>f__AnonymousType7`2 <>h__TransparentIdentifier1) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\ItemController.cs:línea 115
   en System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   en System.Linq.Enumerable.<TakeIterator>d__24`1.MoveNext()
   en System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   en System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   en Proveduria.Controllers.ItemController.SearchItemsFiltro(String filtro, String pagina) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\ItemController.cs:línea 112 
 
              Stack Trace   :    en Proveduria.Controllers.ItemController.<>c.<SearchItemsFiltro>b__5_6(<>f__AnonymousType7`2 <>h__TransparentIdentifier1) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\ItemController.cs:línea 115
   en System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   en System.Linq.Enumerable.<TakeIterator>d__24`1.MoveNext()
   en System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   en System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   en Proveduria.Controllers.ItemController.SearchItemsFiltro(String filtro, String pagina) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\ItemController.cs:línea 112
        
              Additional Info  : Referencia a objeto no establecida como instancia de un objeto.  
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Error(2018-11-29 10:33:22.5696) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : System.NullReferenceException
      
              Exception Message : Referencia a objeto no establecida como instancia de un objeto.
     
              Inner Exception  : System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Proveduria.Controllers.MovimientoController.Movimiento(Int32 id) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\MovimientoController.cs:línea 344 
 
              Stack Trace   :    en Proveduria.Controllers.MovimientoController.Movimiento(Int32 id) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\MovimientoController.cs:línea 344
        
              Additional Info  : Referencia a objeto no establecida como instancia de un objeto.  
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Error(2018-11-29 10:34:37.1951) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : System.NullReferenceException
      
              Exception Message : Referencia a objeto no establecida como instancia de un objeto.
     
              Inner Exception  : System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Proveduria.Controllers.MovimientoController.Movimiento(Int32 id) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\MovimientoController.cs:línea 344 
 
              Stack Trace   :    en Proveduria.Controllers.MovimientoController.Movimiento(Int32 id) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\MovimientoController.cs:línea 344
        
              Additional Info  : Referencia a objeto no establecida como instancia de un objeto.  
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Error(2018-11-29 11:06:08.6912) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : System.InvalidOperationException
      
              Exception Message : The entity type ApplicationUser is not part of the model for the current context.
     
              Inner Exception  : System.InvalidOperationException: The entity type ApplicationUser is not part of the model for the current context.
   en System.Data.Entity.Internal.InternalContext.UpdateEntitySetMappingsForType(Type entityType)
   en System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   en System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   en System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   en System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   en System.Data.Entity.QueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   en System.Data.Entity.QueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate)
   en Microsoft.AspNet.Identity.EntityFramework.UserStore`6.<GetUserAggregateAsync>d__6c.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.AspNet.Identity.TaskExtensions.CultureAwaiter`1.GetResult()
   en Microsoft.AspNet.Identity.UserValidator`2.<ValidateUserName>d__4.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.AspNet.Identity.UserValidator`2.<ValidateAsync>d__0.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.AspNet.Identity.UserManager`2.<CreateAsync>d__0.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.AspNet.Identity.UserManager`2.<CreateAsync>d__d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.AspNet.Identity.AsyncHelper.RunSync[TResult](Func`1 func)
   en Microsoft.AspNet.Identity.UserManagerExtensions.Create[TUser,TKey](UserManager`2 manager, TUser user, String password)
   en Proveduria.Controllers.AccountController.LogOn(LogOnModel model, String returnUrl) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\AccountController.cs:línea 72 
 
              Stack Trace   :    en System.Data.Entity.Internal.InternalContext.UpdateEntitySetMappingsForType(Type entityType)
   en System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   en System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   en System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   en System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   en System.Data.Entity.QueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   en System.Data.Entity.QueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate)
   en Microsoft.AspNet.Identity.EntityFramework.UserStore`6.<GetUserAggregateAsync>d__6c.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.AspNet.Identity.TaskExtensions.CultureAwaiter`1.GetResult()
   en Microsoft.AspNet.Identity.UserValidator`2.<ValidateUserName>d__4.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.AspNet.Identity.UserValidator`2.<ValidateAsync>d__0.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.AspNet.Identity.UserManager`2.<CreateAsync>d__0.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.AspNet.Identity.UserManager`2.<CreateAsync>d__d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.AspNet.Identity.AsyncHelper.RunSync[TResult](Func`1 func)
   en Microsoft.AspNet.Identity.UserManagerExtensions.Create[TUser,TKey](UserManager`2 manager, TUser user, String password)
   en Proveduria.Controllers.AccountController.LogOn(LogOnModel model, String returnUrl) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\AccountController.cs:línea 72
        
              Additional Info  : The entity type ApplicationUser is not part of the model for the current context.  
              -------------------------------------------------------------------
              ----------     
     
